### ISSUE TITLE
虚拟环境可否采用poetry管理

### ISSUE THREAD

**Issue by ericz15** [luizyao/pytest-chinese-doc#3]
目前实际用下来，poetry管理python虚拟环境似乎更加方便～不知道作者有没有意愿切换过来，或者后续有空我提交个pull request修改下？

**Comment by luizyao** [comment]
首先，谢谢你对这个项目的关注。

它的环境依赖其实非常简单，只有 `pytest=5.1.3`，我觉得不管是使用 pipenv 还是 poetry 没什么区别，甚至是 requirements.txt。
 我后续会把文档中每个命令前面的 `pipenv run` 删掉，以避免引起误解。
